services:
  tutor_backend:
    container_name: tutor_backend
    cpus: 1
    mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5008:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - REFRESH_EXPIRES_IN=${REFRESH_EXPIRES_IN}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - ACCESS_EXPIRES_IN=${ACCESS_EXPIRES_IN}
      - ADMIN_REGISTRATION_SECRET_KEY=${ADMIN_REGISTRATION_SECRET_KEY}
      - ORIGIN_URLS=${ORIGIN_URLS}
    networks:
      - tutor_network

  tutor_frontend:
    container_name: tutor_frontend
    cpus: 1
    mem_limit: 512m
    restart: unless-stopped
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - tutor_backend
    ports:
      - 3008:3000
    networks:
      - tutor_network

  tutor_postgres:
    image: postgres:17
    container_name: tutor_postgres
    cpus: 1
    mem_limit: 512m
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5436:5432"
    volumes:
      - tutor_postgres:/var/lib/postgresql/data
    networks:
      - tutor_network

  tutor_backup:
    image: postgres:17
    container_name: tutor_backup
    cpus: 1
    mem_limit: 512m
    restart: unless-stopped
    depends_on:
      - tutor_postgres
    volumes:
      - ./db_backups:/home/akiro/backups
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: >
      bash -c "echo '0 3 * * * pg_dump -h tutor_postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -F c -f /backups/db_$(date +\%F).dump' | crontab - && cron -f"
    networks:
      - tutor_network

volumes:
  tutor_postgres:

networks:
  tutor_network:
